package bahamas.entity;

import java.util.*;
import javax.persistence.*;
import java.util.HashSet;
import java.util.Set;

/**
 * PermissionLevelList generated by hbm2java
 */
@Entity
@Table(name="PERMISSION_LEVEL_LIST")
public class PermissionLevelList  implements java.io.Serializable {

    @Column(name="PERMISSION")
     private String permission;
    @Column(name="DESCRIPTION")
     private String description;
     private Set<TeamJoin> teamJoins = new HashSet<TeamJoin>(0);

    public PermissionLevelList() {
    }

	
    public PermissionLevelList(String permission) {
        this.permission = permission;
    }
    public PermissionLevelList(String permission, String description, Set<TeamJoin> teamJoins) {
       this.permission = permission;
       this.description = description;
       this.teamJoins = teamJoins;
    }
   
    public String getPermission() {
        return this.permission;
    }
    
    public void setPermission(String permission) {
        this.permission = permission;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Set<TeamJoin> getTeamJoins() {
        return this.teamJoins;
    }
    
    public void setTeamJoins(Set<TeamJoin> teamJoins) {
        this.teamJoins = teamJoins;
    }




}


