package bahamas.entity;

import java.util.*;
import javax.persistence.*;
import java.util.Date;

/**
 * Phone generated by hbm2java
 */
@Entity
@Table(name="PHONE")
public class Phone implements java.io.Serializable {
    @Column(name="CONTACT_ID")
     private int contactId;
    @Column(name="PHONE_NUMBER")
     private String phoneNumber;
    @Column(name="DATE_CREATED")
     private Date dateCreated;
    @Column(name="CREATED_BY")
     private String createdBy;
    @Column(name="COUNTRY_CODE")
     private String countryCode;
    @Column(name="REMARKS")
     private String remarks;
    @Column(name="DATE_OBSOLETE")
     private Date dateObsolete;

    public Phone() {
    }

    public Phone(int contactId, String phoneNumber, Date dateCreated, String createdBy, String countryCode, String remarks, Date dateObsolete) {
        this.contactId = contactId;
        this.phoneNumber = phoneNumber;
        this.dateCreated = dateCreated;
        this.createdBy = createdBy;
        this.countryCode = countryCode;
        this.remarks = remarks;
        this.dateObsolete = dateObsolete;
    }

    public int getContactId() {
        return contactId;
    }

    public void setContactId(int contactId) {
        this.contactId = contactId;
    }

    public String getPhoneNumber() {
        return phoneNumber;
    }

    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    public Date getDateCreated() {
        return dateCreated;
    }

    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }

    public String getCreatedBy() {
        return createdBy;
    }

    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    public String getCountryCode() {
        return countryCode;
    }

    public void setCountryCode(String countryCode) {
        this.countryCode = countryCode;
    }

    public String getRemarks() {
        return remarks;
    }

    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    public Date getDateObsolete() {
        return dateObsolete;
    }

    public void setDateObsolete(Date dateObsolete) {
        this.dateObsolete = dateObsolete;
    }
    
    

    
	
    