package bahamas.entity;

import java.util.*;
import javax.persistence.*;
import java.util.Date;

/**
 * Proxy generated by hbm2java
 */
@Entity
@Table(name="PROXY")
public class Proxy implements java.io.Serializable {

    @Column(name="CONTACT_ID")
     private int contactId;
    @Column(name="PROXY_ID")
     private int proxyId;
    @Column(name="CREATED_BY")
     private String createdBy;
    @Column(name="PROXY_STANDING")
     private String proxyStanding;
    @Column(name="DATE_OBSOLETE")
     private Date dateObsolete;
    @Column(name="REMARKS")
     private String remarks;

    public Proxy() {
    }

    public Proxy(int contactId, int proxyId, String createdBy, String proxyStanding, Date dateObsolete, String remarks) {
        this.contactId = contactId;
        this.proxyId = proxyId;
        this.createdBy = createdBy;
        this.proxyStanding = proxyStanding;
        this.dateObsolete = dateObsolete;
        this.remarks = remarks;
    }

    public int getContactId() {
        return contactId;
    }

    public void setContactId(int contactId) {
        this.contactId = contactId;
    }

    public int getProxyId() {
        return proxyId;
    }

    public void setProxyId(int proxyId) {
        this.proxyId = proxyId;
    }

    public String getCreatedBy() {
        return createdBy;
    }

    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    public String getProxyStanding() {
        return proxyStanding;
    }

    public void setProxyStanding(String proxyStanding) {
        this.proxyStanding = proxyStanding;
    }

    public Date getDateObsolete() {
        return dateObsolete;
    }

    public void setDateObsolete(Date dateObsolete) {
        this.dateObsolete = dateObsolete;
    }

    public String getRemarks() {
        return remarks;
    }

    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

	
    