package bahamas.entity;

import bahamas.entity.LsaClassList;
import java.util.*;
import javax.persistence.*;
import java.util.Date;

/**
 * SkillAssignment generated by hbm2java
 */
@Entity
@Table(name="SKILL_ASSIGNMENT")
public class SkillAssignment  implements java.io.Serializable {

    @Column(name="CONTACT_ID")
     private int contactId;
    @Column(name="SKILL_NAME")
     private String skillName;
    
     private LsaClassList lsaClassList;
     @Column(name="DATE_CREATED")
     private Date dateCreated;
     @Column(name="CREATED_BY")
     private String createdBy;
     @Column(name="EXPLAIN_IF_OTHER")
     private String explainIfOther;
     @Column(name="DATE_OBSOLETE")
     private Date dateObsolete;
     @Column(name="REMARKS")
     private String remarks;

    public SkillAssignment() {
    }

    public SkillAssignment(int contactId, String skillName, LsaClassList lsaClassList, Date dateCreated, String createdBy, String explainIfOther, Date dateObsolete, String remarks) {
        this.contactId = contactId;
        this.skillName = skillName;
        this.lsaClassList = lsaClassList;
        this.dateCreated = dateCreated;
        this.createdBy = createdBy;
        this.explainIfOther = explainIfOther;
        this.dateObsolete = dateObsolete;
        this.remarks = remarks;
    }

    public int getContactId() {
        return contactId;
    }

    public void setContactId(int contactId) {
        this.contactId = contactId;
    }

    public String getSkillName() {
        return skillName;
    }

    public void setSkillName(String skillName) {
        this.skillName = skillName;
    }

    public LsaClassList getLsaClassList() {
        return lsaClassList;
    }

    public void setLsaClassList(LsaClassList lsaClassList) {
        this.lsaClassList = lsaClassList;
    }

    public Date getDateCreated() {
        return dateCreated;
    }

    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }

    public String getCreatedBy() {
        return createdBy;
    }

    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    public String getExplainIfOther() {
        return explainIfOther;
    }

    public void setExplainIfOther(String explainIfOther) {
        this.explainIfOther = explainIfOther;
    }

    public Date getDateObsolete() {
        return dateObsolete;
    }

    public void setDateObsolete(Date dateObsolete) {
        this.dateObsolete = dateObsolete;
    }

    public String getRemarks() {
        return remarks;
    }

    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }
    
    
	
    

}


