package bahamas.entity;

import java.util.*;
import javax.persistence.*;
import java.util.HashSet;
import java.util.Set;

/**
 * TeamAffiliationList generated by hbm2java
 */
@Entity
@Table(name="TEAM_AFFILIATION_LIST")
public class TeamAffiliationList  implements java.io.Serializable {

    @Column(name="TEAM_NAME")
     private String teamName;
    @Column(name="DESCRIPTION")
     private String description;
     private Set<TeamJoin> teamJoins = new HashSet<TeamJoin>(0);
     private Set<EventAffiliation> eventAffiliations = new HashSet<EventAffiliation>(0);

    public TeamAffiliationList() {
    }

	
    public TeamAffiliationList(String teamName) {
        this.teamName = teamName;
    }
    public TeamAffiliationList(String teamName, String description, Set<TeamJoin> teamJoins, Set<EventAffiliation> eventAffiliations) {
       this.teamName = teamName;
       this.description = description;
       this.teamJoins = teamJoins;
       this.eventAffiliations = eventAffiliations;
    }
   
    public String getTeamName() {
        return this.teamName;
    }
    
    public void setTeamName(String teamName) {
        this.teamName = teamName;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Set<TeamJoin> getTeamJoins() {
        return this.teamJoins;
    }
    
    public void setTeamJoins(Set<TeamJoin> teamJoins) {
        this.teamJoins = teamJoins;
    }
    public Set<EventAffiliation> getEventAffiliations() {
        return this.eventAffiliations;
    }
    
    public void setEventAffiliations(Set<EventAffiliation> eventAffiliations) {
        this.eventAffiliations = eventAffiliations;
    }




}


