package bahamas.entity;

import java.util.*;
import javax.persistence.*;
import java.util.HashSet;
import java.util.Set;

/**
 * TypeOfContactList generated by hbm2java
 */
@Entity
@Table(name="TYPE_OF_CONTACT_LIST")
public class TypeOfContactList  implements java.io.Serializable {

    @Column(name="CONTACT_TYPE")
     private String contactType;
     private Set<Contact> contacts = new HashSet<Contact>(0);

    public TypeOfContactList() {
    }

	
    public TypeOfContactList(String contactType) {
        this.contactType = contactType;
    }
    public TypeOfContactList(String contactType, Set<Contact> contacts) {
       this.contactType = contactType;
       this.contacts = contacts;
    }
   
    public String getContactType() {
        return this.contactType;
    }
    
    public void setContactType(String contactType) {
        this.contactType = contactType;
    }
    public Set<Contact> getContacts() {
        return this.contacts;
    }
    
    public void setContacts(Set<Contact> contacts) {
        this.contacts = contacts;
    }




}


