CREATE TABLE `FORM` (
  `FORM_ID` int(11) NOT NULL AUTO_INCREMENT,
  `CODE` varchar(20) NOT NULL,
  `DATE_CREATED` datetime NOT NULL,
  `START_DATE_TIME` datetime NOT NULL,
  `END_DATE_TIME` datetime NOT NULL,
  `CREATED_BY` varchar(50) NOT NULL,
  PRIMARY KEY (`FORM_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

CREATE TABLE `REGISTRATION` (
  `REGISTRATION_ID` int(11) NOT NULL AUTO_INCREMENT,
  `FORM_ID` int(11) NOT NULL,
  `CONTACT_ID` int(11) NOT NULL,
  `DATE_CREATED` datetime NOT NULL,
  `NAME` varchar(50) DEFAULT NULL,
  `NRIC_FIN` varchar(9) DEFAULT NULL,
  `NATIONALITY` varchar(20) DEFAULT NULL,
  `DATE_OF_BIRTH` date DEFAULT NULL,
  `GENDER` varchar(1) DEFAULT NULL,
  `PROFESSION` varchar(200) DEFAULT NULL,
  `JOB_TITLE` varchar(50) DEFAULT NULL,
  `REMARKS` varchar(1000) DEFAULT NULL,
  `COUNTRY_CODE` varchar(20) DEFAULT NULL,
  `PHONE_NUMBER` varchar(20) DEFAULT NULL,
  `EMAIL` varchar(50) DEFAULT NULL,
  `LANGUAGE_NAME` varchar(50) DEFAULT NULL,
  `PROFICIENCY` varchar(50) DEFAULT NULL,
  `SKILL_NAME` varchar(50) DEFAULT NULL,
  `TEAM_NAME` varchar(50) DEFAULT NULL,
  `FIRST_CHECK` tinyint(1) DEFAULT '0',
  `SECOND_CHECK` tinyint(1) DEFAULT '0',
  `REQUEST_USER` tinyint(1) DEFAULT '1',
  PRIMARY KEY (`REGISTRATION_ID`),
  CONSTRAINT `REGISTRATION_FK1` FOREIGN KEY (`FORM_ID`) REFERENCES `FORM` (`FORM_ID`),
  CONSTRAINT `REGISTRATION_FK2` FOREIGN KEY (`CONTACT_ID`) REFERENCES `CONTACT` (`CONTACT_ID`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;