package hibernate;
// Generated 21 May, 2016 5:04:19 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Address generated by hbm2java
 */
public class Address  implements java.io.Serializable {


     private AddressId id;
     private Contact contact;
     private Date dateCreated;
     private String createdBy;
     private String country;
     private String zipcode;
     private String remarks;
     private Date dateObsolete;

    public Address() {
    }

	
    public Address(AddressId id, Contact contact, Date dateCreated, String createdBy) {
        this.id = id;
        this.contact = contact;
        this.dateCreated = dateCreated;
        this.createdBy = createdBy;
    }
    public Address(AddressId id, Contact contact, Date dateCreated, String createdBy, String country, String zipcode, String remarks, Date dateObsolete) {
       this.id = id;
       this.contact = contact;
       this.dateCreated = dateCreated;
       this.createdBy = createdBy;
       this.country = country;
       this.zipcode = zipcode;
       this.remarks = remarks;
       this.dateObsolete = dateObsolete;
    }
   
    public AddressId getId() {
        return this.id;
    }
    
    public void setId(AddressId id) {
        this.id = id;
    }
    public Contact getContact() {
        return this.contact;
    }
    
    public void setContact(Contact contact) {
        this.contact = contact;
    }
    public Date getDateCreated() {
        return this.dateCreated;
    }
    
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }
    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }
    public String getZipcode() {
        return this.zipcode;
    }
    
    public void setZipcode(String zipcode) {
        this.zipcode = zipcode;
    }
    public String getRemarks() {
        return this.remarks;
    }
    
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }
    public Date getDateObsolete() {
        return this.dateObsolete;
    }
    
    public void setDateObsolete(Date dateObsolete) {
        this.dateObsolete = dateObsolete;
    }




}


