package hibernate;
// Generated 21 May, 2016 5:04:19 PM by Hibernate Tools 4.3.1



/**
 * AddressId generated by hbm2java
 */
public class AddressId  implements java.io.Serializable {


     private int contactId;
     private String address;

    public AddressId() {
    }

    public AddressId(int contactId, String address) {
       this.contactId = contactId;
       this.address = address;
    }
   
    public int getContactId() {
        return this.contactId;
    }
    
    public void setContactId(int contactId) {
        this.contactId = contactId;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AddressId) ) return false;
		 AddressId castOther = ( AddressId ) other; 
         
		 return (this.getContactId()==castOther.getContactId())
 && ( (this.getAddress()==castOther.getAddress()) || ( this.getAddress()!=null && castOther.getAddress()!=null && this.getAddress().equals(castOther.getAddress()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getContactId();
         result = 37 * result + ( getAddress() == null ? 0 : this.getAddress().hashCode() );
         return result;
   }   


}


