package hibernate;
// Generated 14 May, 2016 6:30:30 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Contact generated by hbm2java
 */
public class Contact  implements java.io.Serializable {


     private int contactId;
     private String contactType;
     private String permission;
     private String username;
     private String password;
     private String deactivated;
     private Date dateCreated;
     private String createdBy;
     private String name;
     private String altName;
     private String explainIfOther;
     private String profession;
     private String jobTitle;
     private String nricFin;
     private String gender;
     private String nationality;
     private Date dateOfBirth;
     private String profilePic;
     private String remarks;

    public Contact() {
    }

	
    public Contact(int contactId, String username, String password, String deactivated) {
        this.contactId = contactId;
        this.username = username;
        this.password = password;
        this.deactivated = deactivated;
    }
    public Contact(int contactId, String contactType, String permission, String username, String password, String deactivated, Date dateCreated, String createdBy, String name, String altName, String explainIfOther, String profession, String jobTitle, String nricFin, String gender, String nationality, Date dateOfBirth, String profilePic, String remarks) {
       this.contactId = contactId;
       this.contactType = contactType;
       this.permission = permission;
       this.username = username;
       this.password = password;
       this.deactivated = deactivated;
       this.dateCreated = dateCreated;
       this.createdBy = createdBy;
       this.name = name;
       this.altName = altName;
       this.explainIfOther = explainIfOther;
       this.profession = profession;
       this.jobTitle = jobTitle;
       this.nricFin = nricFin;
       this.gender = gender;
       this.nationality = nationality;
       this.dateOfBirth = dateOfBirth;
       this.profilePic = profilePic;
       this.remarks = remarks;
    }
   
    public int getContactId() {
        return this.contactId;
    }
    
    public void setContactId(int contactId) {
        this.contactId = contactId;
    }
    public String getContactType() {
        return this.contactType;
    }
    
    public void setContactType(String contactType) {
        this.contactType = contactType;
    }
    public String getPermission() {
        return this.permission;
    }
    
    public void setPermission(String permission) {
        this.permission = permission;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getDeactivated() {
        return this.deactivated;
    }
    
    public void setDeactivated(String deactivated) {
        this.deactivated = deactivated;
    }
    public Date getDateCreated() {
        return this.dateCreated;
    }
    
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getAltName() {
        return this.altName;
    }
    
    public void setAltName(String altName) {
        this.altName = altName;
    }
    public String getExplainIfOther() {
        return this.explainIfOther;
    }
    
    public void setExplainIfOther(String explainIfOther) {
        this.explainIfOther = explainIfOther;
    }
    public String getProfession() {
        return this.profession;
    }
    
    public void setProfession(String profession) {
        this.profession = profession;
    }
    public String getJobTitle() {
        return this.jobTitle;
    }
    
    public void setJobTitle(String jobTitle) {
        this.jobTitle = jobTitle;
    }
    public String getNricFin() {
        return this.nricFin;
    }
    
    public void setNricFin(String nricFin) {
        this.nricFin = nricFin;
    }
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }
    public String getNationality() {
        return this.nationality;
    }
    
    public void setNationality(String nationality) {
        this.nationality = nationality;
    }
    public Date getDateOfBirth() {
        return this.dateOfBirth;
    }
    
    public void setDateOfBirth(Date dateOfBirth) {
        this.dateOfBirth = dateOfBirth;
    }
    public String getProfilePic() {
        return this.profilePic;
    }
    
    public void setProfilePic(String profilePic) {
        this.profilePic = profilePic;
    }
    public String getRemarks() {
        return this.remarks;
    }
    
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }




}


