package hibernate;
// Generated 14 May, 2016 6:30:30 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Donation generated by hbm2java
 */
public class Donation  implements java.io.Serializable {


     private int donationId;
     private int contactId;
     private Date dateCreated;
     private Integer createdBy;
     private Date dateReceived;
     private float donationAmount;
     private String paymentModeName;
     private String explainIfOtherPayment;
     private String extTransactionRef;
     private String receiptNumber;
     private Date receiptDate;
     private String explainIfOtherReceipt;
     private String donorInstructions;
     private String allocation1;
     private Float subamount1;
     private String allocation2;
     private Float subamount2;
     private String allocation3;
     private Float subamount3;
     private String associatedOccasion;
     private String remarks;

    public Donation() {
    }

	
    public Donation(int donationId, int contactId, Date dateCreated, Date dateReceived, float donationAmount, String paymentModeName) {
        this.donationId = donationId;
        this.contactId = contactId;
        this.dateCreated = dateCreated;
        this.dateReceived = dateReceived;
        this.donationAmount = donationAmount;
        this.paymentModeName = paymentModeName;
    }
    public Donation(int donationId, int contactId, Date dateCreated, Integer createdBy, Date dateReceived, float donationAmount, String paymentModeName, String explainIfOtherPayment, String extTransactionRef, String receiptNumber, Date receiptDate, String explainIfOtherReceipt, String donorInstructions, String allocation1, Float subamount1, String allocation2, Float subamount2, String allocation3, Float subamount3, String associatedOccasion, String remarks) {
       this.donationId = donationId;
       this.contactId = contactId;
       this.dateCreated = dateCreated;
       this.createdBy = createdBy;
       this.dateReceived = dateReceived;
       this.donationAmount = donationAmount;
       this.paymentModeName = paymentModeName;
       this.explainIfOtherPayment = explainIfOtherPayment;
       this.extTransactionRef = extTransactionRef;
       this.receiptNumber = receiptNumber;
       this.receiptDate = receiptDate;
       this.explainIfOtherReceipt = explainIfOtherReceipt;
       this.donorInstructions = donorInstructions;
       this.allocation1 = allocation1;
       this.subamount1 = subamount1;
       this.allocation2 = allocation2;
       this.subamount2 = subamount2;
       this.allocation3 = allocation3;
       this.subamount3 = subamount3;
       this.associatedOccasion = associatedOccasion;
       this.remarks = remarks;
    }
   
    public int getDonationId() {
        return this.donationId;
    }
    
    public void setDonationId(int donationId) {
        this.donationId = donationId;
    }
    public int getContactId() {
        return this.contactId;
    }
    
    public void setContactId(int contactId) {
        this.contactId = contactId;
    }
    public Date getDateCreated() {
        return this.dateCreated;
    }
    
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }
    public Integer getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(Integer createdBy) {
        this.createdBy = createdBy;
    }
    public Date getDateReceived() {
        return this.dateReceived;
    }
    
    public void setDateReceived(Date dateReceived) {
        this.dateReceived = dateReceived;
    }
    public float getDonationAmount() {
        return this.donationAmount;
    }
    
    public void setDonationAmount(float donationAmount) {
        this.donationAmount = donationAmount;
    }
    public String getPaymentModeName() {
        return this.paymentModeName;
    }
    
    public void setPaymentModeName(String paymentModeName) {
        this.paymentModeName = paymentModeName;
    }
    public String getExplainIfOtherPayment() {
        return this.explainIfOtherPayment;
    }
    
    public void setExplainIfOtherPayment(String explainIfOtherPayment) {
        this.explainIfOtherPayment = explainIfOtherPayment;
    }
    public String getExtTransactionRef() {
        return this.extTransactionRef;
    }
    
    public void setExtTransactionRef(String extTransactionRef) {
        this.extTransactionRef = extTransactionRef;
    }
    public String getReceiptNumber() {
        return this.receiptNumber;
    }
    
    public void setReceiptNumber(String receiptNumber) {
        this.receiptNumber = receiptNumber;
    }
    public Date getReceiptDate() {
        return this.receiptDate;
    }
    
    public void setReceiptDate(Date receiptDate) {
        this.receiptDate = receiptDate;
    }
    public String getExplainIfOtherReceipt() {
        return this.explainIfOtherReceipt;
    }
    
    public void setExplainIfOtherReceipt(String explainIfOtherReceipt) {
        this.explainIfOtherReceipt = explainIfOtherReceipt;
    }
    public String getDonorInstructions() {
        return this.donorInstructions;
    }
    
    public void setDonorInstructions(String donorInstructions) {
        this.donorInstructions = donorInstructions;
    }
    public String getAllocation1() {
        return this.allocation1;
    }
    
    public void setAllocation1(String allocation1) {
        this.allocation1 = allocation1;
    }
    public Float getSubamount1() {
        return this.subamount1;
    }
    
    public void setSubamount1(Float subamount1) {
        this.subamount1 = subamount1;
    }
    public String getAllocation2() {
        return this.allocation2;
    }
    
    public void setAllocation2(String allocation2) {
        this.allocation2 = allocation2;
    }
    public Float getSubamount2() {
        return this.subamount2;
    }
    
    public void setSubamount2(Float subamount2) {
        this.subamount2 = subamount2;
    }
    public String getAllocation3() {
        return this.allocation3;
    }
    
    public void setAllocation3(String allocation3) {
        this.allocation3 = allocation3;
    }
    public Float getSubamount3() {
        return this.subamount3;
    }
    
    public void setSubamount3(Float subamount3) {
        this.subamount3 = subamount3;
    }
    public String getAssociatedOccasion() {
        return this.associatedOccasion;
    }
    
    public void setAssociatedOccasion(String associatedOccasion) {
        this.associatedOccasion = associatedOccasion;
    }
    public String getRemarks() {
        return this.remarks;
    }
    
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }




}


