package hibernate;
// Generated 21 May, 2016 5:04:19 PM by Hibernate Tools 4.3.1



/**
 * EmailId generated by hbm2java
 */
public class EmailId  implements java.io.Serializable {


     private int contactId;
     private String email;

    public EmailId() {
    }

    public EmailId(int contactId, String email) {
       this.contactId = contactId;
       this.email = email;
    }
   
    public int getContactId() {
        return this.contactId;
    }
    
    public void setContactId(int contactId) {
        this.contactId = contactId;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof EmailId) ) return false;
		 EmailId castOther = ( EmailId ) other; 
         
		 return (this.getContactId()==castOther.getContactId())
 && ( (this.getEmail()==castOther.getEmail()) || ( this.getEmail()!=null && castOther.getEmail()!=null && this.getEmail().equals(castOther.getEmail()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getContactId();
         result = 37 * result + ( getEmail() == null ? 0 : this.getEmail().hashCode() );
         return result;
   }   


}


