package hibernate;
// Generated 21 May, 2016 5:04:19 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Email generated by hbm2java
 */
public class Email  implements java.io.Serializable {


     private EmailId id;
     private Contact contact;
     private Date dateCreated;
     private String createdBy;
     private String remarks;
     private Date dateObsolete;

    public Email() {
    }

	
    public Email(EmailId id, Contact contact, String createdBy) {
        this.id = id;
        this.contact = contact;
        this.createdBy = createdBy;
    }
    public Email(EmailId id, Contact contact, Date dateCreated, String createdBy, String remarks, Date dateObsolete) {
       this.id = id;
       this.contact = contact;
       this.dateCreated = dateCreated;
       this.createdBy = createdBy;
       this.remarks = remarks;
       this.dateObsolete = dateObsolete;
    }
   
    public EmailId getId() {
        return this.id;
    }
    
    public void setId(EmailId id) {
        this.id = id;
    }
    public Contact getContact() {
        return this.contact;
    }
    
    public void setContact(Contact contact) {
        this.contact = contact;
    }
    public Date getDateCreated() {
        return this.dateCreated;
    }
    
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }
    public String getRemarks() {
        return this.remarks;
    }
    
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }
    public Date getDateObsolete() {
        return this.dateObsolete;
    }
    
    public void setDateObsolete(Date dateObsolete) {
        this.dateObsolete = dateObsolete;
    }




}


