package hibernate;
// Generated 21 May, 2016 5:04:19 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * EventClassList generated by hbm2java
 */
public class EventClassList  implements java.io.Serializable {


     private String eventClassName;
     private Set<Event> events = new HashSet<Event>(0);

    public EventClassList() {
    }

	
    public EventClassList(String eventClassName) {
        this.eventClassName = eventClassName;
    }
    public EventClassList(String eventClassName, Set<Event> events) {
       this.eventClassName = eventClassName;
       this.events = events;
    }
   
    public String getEventClassName() {
        return this.eventClassName;
    }
    
    public void setEventClassName(String eventClassName) {
        this.eventClassName = eventClassName;
    }
    public Set<Event> getEvents() {
        return this.events;
    }
    
    public void setEvents(Set<Event> events) {
        this.events = events;
    }




}


