package hibernate;
// Generated 14 May, 2016 6:30:30 PM by Hibernate Tools 4.3.1



/**
 * EventLocation generated by hbm2java
 */
public class EventLocation  implements java.io.Serializable {


     private String eventLocationName;

    public EventLocation() {
    }

    public EventLocation(String eventLocationName) {
       this.eventLocationName = eventLocationName;
    }
   
    public String getEventLocationName() {
        return this.eventLocationName;
    }
    
    public void setEventLocationName(String eventLocationName) {
        this.eventLocationName = eventLocationName;
    }




}


