package hibernate;
// Generated 21 May, 2016 5:04:19 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * EventAffiliation generated by hbm2java
 */
public class EventAffiliation  implements java.io.Serializable {


     private EventAffiliationId id;
     private Event event;
     private TeamAffiliationList teamAffiliationList;
     private String createdBy;
     private Date dateCreated;
     private String explainIfOther;
     private Date dateObsolete;
     private String remarks;

    public EventAffiliation() {
    }

	
    public EventAffiliation(EventAffiliationId id, Event event, TeamAffiliationList teamAffiliationList, String createdBy) {
        this.id = id;
        this.event = event;
        this.teamAffiliationList = teamAffiliationList;
        this.createdBy = createdBy;
    }
    public EventAffiliation(EventAffiliationId id, Event event, TeamAffiliationList teamAffiliationList, String createdBy, Date dateCreated, String explainIfOther, Date dateObsolete, String remarks) {
       this.id = id;
       this.event = event;
       this.teamAffiliationList = teamAffiliationList;
       this.createdBy = createdBy;
       this.dateCreated = dateCreated;
       this.explainIfOther = explainIfOther;
       this.dateObsolete = dateObsolete;
       this.remarks = remarks;
    }
   
    public EventAffiliationId getId() {
        return this.id;
    }
    
    public void setId(EventAffiliationId id) {
        this.id = id;
    }
    public Event getEvent() {
        return this.event;
    }
    
    public void setEvent(Event event) {
        this.event = event;
    }
    public TeamAffiliationList getTeamAffiliationList() {
        return this.teamAffiliationList;
    }
    
    public void setTeamAffiliationList(TeamAffiliationList teamAffiliationList) {
        this.teamAffiliationList = teamAffiliationList;
    }
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }
    public Date getDateCreated() {
        return this.dateCreated;
    }
    
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }
    public String getExplainIfOther() {
        return this.explainIfOther;
    }
    
    public void setExplainIfOther(String explainIfOther) {
        this.explainIfOther = explainIfOther;
    }
    public Date getDateObsolete() {
        return this.dateObsolete;
    }
    
    public void setDateObsolete(Date dateObsolete) {
        this.dateObsolete = dateObsolete;
    }
    public String getRemarks() {
        return this.remarks;
    }
    
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }




}


