package hibernate;
// Generated 21 May, 2016 5:04:19 PM by Hibernate Tools 4.3.1



/**
 * EventParticipantId generated by hbm2java
 */
public class EventParticipantId  implements java.io.Serializable {


     private int contactId;
     private int eventId;
     private int roleId;

    public EventParticipantId() {
    }

    public EventParticipantId(int contactId, int eventId, int roleId) {
       this.contactId = contactId;
       this.eventId = eventId;
       this.roleId = roleId;
    }
   
    public int getContactId() {
        return this.contactId;
    }
    
    public void setContactId(int contactId) {
        this.contactId = contactId;
    }
    public int getEventId() {
        return this.eventId;
    }
    
    public void setEventId(int eventId) {
        this.eventId = eventId;
    }
    public int getRoleId() {
        return this.roleId;
    }
    
    public void setRoleId(int roleId) {
        this.roleId = roleId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof EventParticipantId) ) return false;
		 EventParticipantId castOther = ( EventParticipantId ) other; 
         
		 return (this.getContactId()==castOther.getContactId())
 && (this.getEventId()==castOther.getEventId())
 && (this.getRoleId()==castOther.getRoleId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getContactId();
         result = 37 * result + this.getEventId();
         result = 37 * result + this.getRoleId();
         return result;
   }   


}


