package hibernate;
// Generated 21 May, 2016 5:04:19 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Event generated by hbm2java
 */
public class Event  implements java.io.Serializable {


     private int eventId;
     private EventClassList eventClassList;
     private EventLocationList eventLocationList;
     private String createdBy;
     private Date dateCreated;
     private String eventTitle;
     private String explainIfOther;
     private Date eventDate;
     private Date eventTimeStart;
     private Date eventTimeEnd;
     private String sendReminder;
     private String eventDescription;
     private Integer minimumParticipations;
     private Set<Notice> notices = new HashSet<Notice>(0);
     private Set<TrainingCertificated> trainingCertificateds = new HashSet<TrainingCertificated>(0);
     private Set<RoleList> roleLists = new HashSet<RoleList>(0);
     private Set<EventAffiliation> eventAffiliations = new HashSet<EventAffiliation>(0);
     private Set<EventParticipant> eventParticipants = new HashSet<EventParticipant>(0);

    public Event() {
    }

	
    public Event(int eventId, EventClassList eventClassList, EventLocationList eventLocationList, String createdBy, String eventTitle, Date eventDate, Date eventTimeStart, Date eventTimeEnd, String sendReminder) {
        this.eventId = eventId;
        this.eventClassList = eventClassList;
        this.eventLocationList = eventLocationList;
        this.createdBy = createdBy;
        this.eventTitle = eventTitle;
        this.eventDate = eventDate;
        this.eventTimeStart = eventTimeStart;
        this.eventTimeEnd = eventTimeEnd;
        this.sendReminder = sendReminder;
    }
    public Event(int eventId, EventClassList eventClassList, EventLocationList eventLocationList, String createdBy, Date dateCreated, String eventTitle, String explainIfOther, Date eventDate, Date eventTimeStart, Date eventTimeEnd, String sendReminder, String eventDescription, Integer minimumParticipations, Set<Notice> notices, Set<TrainingCertificated> trainingCertificateds, Set<RoleList> roleLists, Set<EventAffiliation> eventAffiliations, Set<EventParticipant> eventParticipants) {
       this.eventId = eventId;
       this.eventClassList = eventClassList;
       this.eventLocationList = eventLocationList;
       this.createdBy = createdBy;
       this.dateCreated = dateCreated;
       this.eventTitle = eventTitle;
       this.explainIfOther = explainIfOther;
       this.eventDate = eventDate;
       this.eventTimeStart = eventTimeStart;
       this.eventTimeEnd = eventTimeEnd;
       this.sendReminder = sendReminder;
       this.eventDescription = eventDescription;
       this.minimumParticipations = minimumParticipations;
       this.notices = notices;
       this.trainingCertificateds = trainingCertificateds;
       this.roleLists = roleLists;
       this.eventAffiliations = eventAffiliations;
       this.eventParticipants = eventParticipants;
    }
   
    public int getEventId() {
        return this.eventId;
    }
    
    public void setEventId(int eventId) {
        this.eventId = eventId;
    }
    public EventClassList getEventClassList() {
        return this.eventClassList;
    }
    
    public void setEventClassList(EventClassList eventClassList) {
        this.eventClassList = eventClassList;
    }
    public EventLocationList getEventLocationList() {
        return this.eventLocationList;
    }
    
    public void setEventLocationList(EventLocationList eventLocationList) {
        this.eventLocationList = eventLocationList;
    }
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }
    public Date getDateCreated() {
        return this.dateCreated;
    }
    
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }
    public String getEventTitle() {
        return this.eventTitle;
    }
    
    public void setEventTitle(String eventTitle) {
        this.eventTitle = eventTitle;
    }
    public String getExplainIfOther() {
        return this.explainIfOther;
    }
    
    public void setExplainIfOther(String explainIfOther) {
        this.explainIfOther = explainIfOther;
    }
    public Date getEventDate() {
        return this.eventDate;
    }
    
    public void setEventDate(Date eventDate) {
        this.eventDate = eventDate;
    }
    public Date getEventTimeStart() {
        return this.eventTimeStart;
    }
    
    public void setEventTimeStart(Date eventTimeStart) {
        this.eventTimeStart = eventTimeStart;
    }
    public Date getEventTimeEnd() {
        return this.eventTimeEnd;
    }
    
    public void setEventTimeEnd(Date eventTimeEnd) {
        this.eventTimeEnd = eventTimeEnd;
    }
    public String getSendReminder() {
        return this.sendReminder;
    }
    
    public void setSendReminder(String sendReminder) {
        this.sendReminder = sendReminder;
    }
    public String getEventDescription() {
        return this.eventDescription;
    }
    
    public void setEventDescription(String eventDescription) {
        this.eventDescription = eventDescription;
    }
    public Integer getMinimumParticipations() {
        return this.minimumParticipations;
    }
    
    public void setMinimumParticipations(Integer minimumParticipations) {
        this.minimumParticipations = minimumParticipations;
    }
    public Set<Notice> getNotices() {
        return this.notices;
    }
    
    public void setNotices(Set<Notice> notices) {
        this.notices = notices;
    }
    public Set<TrainingCertificated> getTrainingCertificateds() {
        return this.trainingCertificateds;
    }
    
    public void setTrainingCertificateds(Set<TrainingCertificated> trainingCertificateds) {
        this.trainingCertificateds = trainingCertificateds;
    }
    public Set<RoleList> getRoleLists() {
        return this.roleLists;
    }
    
    public void setRoleLists(Set<RoleList> roleLists) {
        this.roleLists = roleLists;
    }
    public Set<EventAffiliation> getEventAffiliations() {
        return this.eventAffiliations;
    }
    
    public void setEventAffiliations(Set<EventAffiliation> eventAffiliations) {
        this.eventAffiliations = eventAffiliations;
    }
    public Set<EventParticipant> getEventParticipants() {
        return this.eventParticipants;
    }
    
    public void setEventParticipants(Set<EventParticipant> eventParticipants) {
        this.eventParticipants = eventParticipants;
    }




}


