package hibernate;
// Generated 21 May, 2016 5:04:19 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * EventParticipant generated by hbm2java
 */
public class EventParticipant  implements java.io.Serializable {


     private EventParticipantId id;
     private Contact contactByAwarderId;
     private Contact contactByContactId;
     private Event event;
     private RoleList roleList;
     private String createdBy;
     private Date dateCreated;
     private String pullout;
     private Date datePullout;
     private String reason;
     private Float hoursServed;
     private String serviceComment;
     private String remarks;

    public EventParticipant() {
    }

	
    public EventParticipant(EventParticipantId id, Contact contactByContactId, Event event, RoleList roleList, String createdBy) {
        this.id = id;
        this.contactByContactId = contactByContactId;
        this.event = event;
        this.roleList = roleList;
        this.createdBy = createdBy;
    }
    public EventParticipant(EventParticipantId id, Contact contactByAwarderId, Contact contactByContactId, Event event, RoleList roleList, String createdBy, Date dateCreated, String pullout, Date datePullout, String reason, Float hoursServed, String serviceComment, String remarks) {
       this.id = id;
       this.contactByAwarderId = contactByAwarderId;
       this.contactByContactId = contactByContactId;
       this.event = event;
       this.roleList = roleList;
       this.createdBy = createdBy;
       this.dateCreated = dateCreated;
       this.pullout = pullout;
       this.datePullout = datePullout;
       this.reason = reason;
       this.hoursServed = hoursServed;
       this.serviceComment = serviceComment;
       this.remarks = remarks;
    }
   
    public EventParticipantId getId() {
        return this.id;
    }
    
    public void setId(EventParticipantId id) {
        this.id = id;
    }
    public Contact getContactByAwarderId() {
        return this.contactByAwarderId;
    }
    
    public void setContactByAwarderId(Contact contactByAwarderId) {
        this.contactByAwarderId = contactByAwarderId;
    }
    public Contact getContactByContactId() {
        return this.contactByContactId;
    }
    
    public void setContactByContactId(Contact contactByContactId) {
        this.contactByContactId = contactByContactId;
    }
    public Event getEvent() {
        return this.event;
    }
    
    public void setEvent(Event event) {
        this.event = event;
    }
    public RoleList getRoleList() {
        return this.roleList;
    }
    
    public void setRoleList(RoleList roleList) {
        this.roleList = roleList;
    }
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }
    public Date getDateCreated() {
        return this.dateCreated;
    }
    
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }
    public String getPullout() {
        return this.pullout;
    }
    
    public void setPullout(String pullout) {
        this.pullout = pullout;
    }
    public Date getDatePullout() {
        return this.datePullout;
    }
    
    public void setDatePullout(Date datePullout) {
        this.datePullout = datePullout;
    }
    public String getReason() {
        return this.reason;
    }
    
    public void setReason(String reason) {
        this.reason = reason;
    }
    public Float getHoursServed() {
        return this.hoursServed;
    }
    
    public void setHoursServed(Float hoursServed) {
        this.hoursServed = hoursServed;
    }
    public String getServiceComment() {
        return this.serviceComment;
    }
    
    public void setServiceComment(String serviceComment) {
        this.serviceComment = serviceComment;
    }
    public String getRemarks() {
        return this.remarks;
    }
    
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }




}


