package hibernate;
// Generated 14 May, 2016 6:30:30 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Event generated by hbm2java
 */
public class Event  implements java.io.Serializable {


     private int eventId;
     private Integer createdBy;
     private Date dateCreated;
     private String eventTitle;
     private String explainIfOther;
     private Date eventDate;
     private Date eventTimeStart;
     private Date eventTimeEnd;
     private String sendReminder;
     private String eventDescription;
     private Integer minimumParticipations;
     private String eventClassName;
     private String eventLocationName;
     private String remarks;

    public Event() {
    }

	
    public Event(int eventId, String eventTitle, Date eventDate, Date eventTimeStart, Date eventTimeEnd, String sendReminder, String eventLocationName) {
        this.eventId = eventId;
        this.eventTitle = eventTitle;
        this.eventDate = eventDate;
        this.eventTimeStart = eventTimeStart;
        this.eventTimeEnd = eventTimeEnd;
        this.sendReminder = sendReminder;
        this.eventLocationName = eventLocationName;
    }
    public Event(int eventId, Integer createdBy, Date dateCreated, String eventTitle, String explainIfOther, Date eventDate, Date eventTimeStart, Date eventTimeEnd, String sendReminder, String eventDescription, Integer minimumParticipations, String eventClassName, String eventLocationName, String remarks) {
       this.eventId = eventId;
       this.createdBy = createdBy;
       this.dateCreated = dateCreated;
       this.eventTitle = eventTitle;
       this.explainIfOther = explainIfOther;
       this.eventDate = eventDate;
       this.eventTimeStart = eventTimeStart;
       this.eventTimeEnd = eventTimeEnd;
       this.sendReminder = sendReminder;
       this.eventDescription = eventDescription;
       this.minimumParticipations = minimumParticipations;
       this.eventClassName = eventClassName;
       this.eventLocationName = eventLocationName;
       this.remarks = remarks;
    }
   
    public int getEventId() {
        return this.eventId;
    }
    
    public void setEventId(int eventId) {
        this.eventId = eventId;
    }
    public Integer getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(Integer createdBy) {
        this.createdBy = createdBy;
    }
    public Date getDateCreated() {
        return this.dateCreated;
    }
    
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }
    public String getEventTitle() {
        return this.eventTitle;
    }
    
    public void setEventTitle(String eventTitle) {
        this.eventTitle = eventTitle;
    }
    public String getExplainIfOther() {
        return this.explainIfOther;
    }
    
    public void setExplainIfOther(String explainIfOther) {
        this.explainIfOther = explainIfOther;
    }
    public Date getEventDate() {
        return this.eventDate;
    }
    
    public void setEventDate(Date eventDate) {
        this.eventDate = eventDate;
    }
    public Date getEventTimeStart() {
        return this.eventTimeStart;
    }
    
    public void setEventTimeStart(Date eventTimeStart) {
        this.eventTimeStart = eventTimeStart;
    }
    public Date getEventTimeEnd() {
        return this.eventTimeEnd;
    }
    
    public void setEventTimeEnd(Date eventTimeEnd) {
        this.eventTimeEnd = eventTimeEnd;
    }
    public String getSendReminder() {
        return this.sendReminder;
    }
    
    public void setSendReminder(String sendReminder) {
        this.sendReminder = sendReminder;
    }
    public String getEventDescription() {
        return this.eventDescription;
    }
    
    public void setEventDescription(String eventDescription) {
        this.eventDescription = eventDescription;
    }
    public Integer getMinimumParticipations() {
        return this.minimumParticipations;
    }
    
    public void setMinimumParticipations(Integer minimumParticipations) {
        this.minimumParticipations = minimumParticipations;
    }
    public String getEventClassName() {
        return this.eventClassName;
    }
    
    public void setEventClassName(String eventClassName) {
        this.eventClassName = eventClassName;
    }
    public String getEventLocationName() {
        return this.eventLocationName;
    }
    
    public void setEventLocationName(String eventLocationName) {
        this.eventLocationName = eventLocationName;
    }
    public String getRemarks() {
        return this.remarks;
    }
    
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }




}


