package hibernate;
// Generated 14 May, 2016 6:30:30 PM by Hibernate Tools 4.3.1



/**
 * EventClass generated by hbm2java
 */
public class EventClass  implements java.io.Serializable {


     private String eventClassName;

    public EventClass() {
    }

    public EventClass(String eventClassName) {
       this.eventClassName = eventClassName;
    }
   
    public String getEventClassName() {
        return this.eventClassName;
    }
    
    public void setEventClassName(String eventClassName) {
        this.eventClassName = eventClassName;
    }




}


