package hibernate;
// Generated 21 May, 2016 5:04:19 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * EventLocationList generated by hbm2java
 */
public class EventLocationList  implements java.io.Serializable {


     private String eventLocationName;
     private Set<Event> events = new HashSet<Event>(0);

    public EventLocationList() {
    }

	
    public EventLocationList(String eventLocationName) {
        this.eventLocationName = eventLocationName;
    }
    public EventLocationList(String eventLocationName, Set<Event> events) {
       this.eventLocationName = eventLocationName;
       this.events = events;
    }
   
    public String getEventLocationName() {
        return this.eventLocationName;
    }
    
    public void setEventLocationName(String eventLocationName) {
        this.eventLocationName = eventLocationName;
    }
    public Set<Event> getEvents() {
        return this.events;
    }
    
    public void setEvents(Set<Event> events) {
        this.events = events;
    }




}


