package hibernate;
// Generated 21 May, 2016 5:04:19 PM by Hibernate Tools 4.3.1



/**
 * LanguageAssignmentId generated by hbm2java
 */
public class LanguageAssignmentId  implements java.io.Serializable {


     private int contactId;
     private String languageName;

    public LanguageAssignmentId() {
    }

    public LanguageAssignmentId(int contactId, String languageName) {
       this.contactId = contactId;
       this.languageName = languageName;
    }
   
    public int getContactId() {
        return this.contactId;
    }
    
    public void setContactId(int contactId) {
        this.contactId = contactId;
    }
    public String getLanguageName() {
        return this.languageName;
    }
    
    public void setLanguageName(String languageName) {
        this.languageName = languageName;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof LanguageAssignmentId) ) return false;
		 LanguageAssignmentId castOther = ( LanguageAssignmentId ) other; 
         
		 return (this.getContactId()==castOther.getContactId())
 && ( (this.getLanguageName()==castOther.getLanguageName()) || ( this.getLanguageName()!=null && castOther.getLanguageName()!=null && this.getLanguageName().equals(castOther.getLanguageName()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getContactId();
         result = 37 * result + ( getLanguageName() == null ? 0 : this.getLanguageName().hashCode() );
         return result;
   }   


}


