package hibernate;
// Generated 21 May, 2016 5:04:19 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * LanguageList generated by hbm2java
 */
public class LanguageList  implements java.io.Serializable {


     private String languageName;
     private Set<LanguageAssignment> languageAssignments = new HashSet<LanguageAssignment>(0);

    public LanguageList() {
    }

	
    public LanguageList(String languageName) {
        this.languageName = languageName;
    }
    public LanguageList(String languageName, Set<LanguageAssignment> languageAssignments) {
       this.languageName = languageName;
       this.languageAssignments = languageAssignments;
    }
   
    public String getLanguageName() {
        return this.languageName;
    }
    
    public void setLanguageName(String languageName) {
        this.languageName = languageName;
    }
    public Set<LanguageAssignment> getLanguageAssignments() {
        return this.languageAssignments;
    }
    
    public void setLanguageAssignments(Set<LanguageAssignment> languageAssignments) {
        this.languageAssignments = languageAssignments;
    }




}


