package hibernate;
// Generated 14 May, 2016 6:30:30 PM by Hibernate Tools 4.3.1



/**
 * Language generated by hbm2java
 */
public class Language  implements java.io.Serializable {


     private String languageName;

    public Language() {
    }

    public Language(String languageName) {
       this.languageName = languageName;
    }
   
    public String getLanguageName() {
        return this.languageName;
    }
    
    public void setLanguageName(String languageName) {
        this.languageName = languageName;
    }




}


