package hibernate;
// Generated 21 May, 2016 5:04:19 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * LanguageAssignment generated by hbm2java
 */
public class LanguageAssignment  implements java.io.Serializable {


     private LanguageAssignmentId id;
     private Contact contact;
     private LanguageList languageList;
     private Date dateCreated;
     private String createdBy;
     private String explainIfOther;
     private Date dateObsolete;
     private String proficiency;
     private String remarks;

    public LanguageAssignment() {
    }

	
    public LanguageAssignment(LanguageAssignmentId id, Contact contact, LanguageList languageList, String createdBy) {
        this.id = id;
        this.contact = contact;
        this.languageList = languageList;
        this.createdBy = createdBy;
    }
    public LanguageAssignment(LanguageAssignmentId id, Contact contact, LanguageList languageList, Date dateCreated, String createdBy, String explainIfOther, Date dateObsolete, String proficiency, String remarks) {
       this.id = id;
       this.contact = contact;
       this.languageList = languageList;
       this.dateCreated = dateCreated;
       this.createdBy = createdBy;
       this.explainIfOther = explainIfOther;
       this.dateObsolete = dateObsolete;
       this.proficiency = proficiency;
       this.remarks = remarks;
    }
   
    public LanguageAssignmentId getId() {
        return this.id;
    }
    
    public void setId(LanguageAssignmentId id) {
        this.id = id;
    }
    public Contact getContact() {
        return this.contact;
    }
    
    public void setContact(Contact contact) {
        this.contact = contact;
    }
    public LanguageList getLanguageList() {
        return this.languageList;
    }
    
    public void setLanguageList(LanguageList languageList) {
        this.languageList = languageList;
    }
    public Date getDateCreated() {
        return this.dateCreated;
    }
    
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }
    public String getExplainIfOther() {
        return this.explainIfOther;
    }
    
    public void setExplainIfOther(String explainIfOther) {
        this.explainIfOther = explainIfOther;
    }
    public Date getDateObsolete() {
        return this.dateObsolete;
    }
    
    public void setDateObsolete(Date dateObsolete) {
        this.dateObsolete = dateObsolete;
    }
    public String getProficiency() {
        return this.proficiency;
    }
    
    public void setProficiency(String proficiency) {
        this.proficiency = proficiency;
    }
    public String getRemarks() {
        return this.remarks;
    }
    
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }




}


