package hibernate;
// Generated 14 May, 2016 6:30:30 PM by Hibernate Tools 4.3.1



/**
 * LsaClass generated by hbm2java
 */
public class LsaClass  implements java.io.Serializable {


     private String skillName;

    public LsaClass() {
    }

    public LsaClass(String skillName) {
       this.skillName = skillName;
    }
   
    public String getSkillName() {
        return this.skillName;
    }
    
    public void setSkillName(String skillName) {
        this.skillName = skillName;
    }




}


