package hibernate;
// Generated 21 May, 2016 5:04:19 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * LsaClassList generated by hbm2java
 */
public class LsaClassList  implements java.io.Serializable {


     private String skillName;
     private Set<SkillAssignment> skillAssignments = new HashSet<SkillAssignment>(0);

    public LsaClassList() {
    }

	
    public LsaClassList(String skillName) {
        this.skillName = skillName;
    }
    public LsaClassList(String skillName, Set<SkillAssignment> skillAssignments) {
       this.skillName = skillName;
       this.skillAssignments = skillAssignments;
    }
   
    public String getSkillName() {
        return this.skillName;
    }
    
    public void setSkillName(String skillName) {
        this.skillName = skillName;
    }
    public Set<SkillAssignment> getSkillAssignments() {
        return this.skillAssignments;
    }
    
    public void setSkillAssignments(Set<SkillAssignment> skillAssignments) {
        this.skillAssignments = skillAssignments;
    }




}


