package hibernate;
// Generated 21 May, 2016 5:04:19 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * MembershipId generated by hbm2java
 */
public class MembershipId  implements java.io.Serializable {


     private int contactId;
     private Date dateCreated;

    public MembershipId() {
    }

    public MembershipId(int contactId, Date dateCreated) {
       this.contactId = contactId;
       this.dateCreated = dateCreated;
    }
   
    public int getContactId() {
        return this.contactId;
    }
    
    public void setContactId(int contactId) {
        this.contactId = contactId;
    }
    public Date getDateCreated() {
        return this.dateCreated;
    }
    
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof MembershipId) ) return false;
		 MembershipId castOther = ( MembershipId ) other; 
         
		 return (this.getContactId()==castOther.getContactId())
 && ( (this.getDateCreated()==castOther.getDateCreated()) || ( this.getDateCreated()!=null && castOther.getDateCreated()!=null && this.getDateCreated().equals(castOther.getDateCreated()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getContactId();
         result = 37 * result + ( getDateCreated() == null ? 0 : this.getDateCreated().hashCode() );
         return result;
   }   


}


