package hibernate;
// Generated 14 May, 2016 6:30:30 PM by Hibernate Tools 4.3.1



/**
 * MembershipClass generated by hbm2java
 */
public class MembershipClass  implements java.io.Serializable {


     private String membershipClassName;

    public MembershipClass() {
    }

    public MembershipClass(String membershipClassName) {
       this.membershipClassName = membershipClassName;
    }
   
    public String getMembershipClassName() {
        return this.membershipClassName;
    }
    
    public void setMembershipClassName(String membershipClassName) {
        this.membershipClassName = membershipClassName;
    }




}


