package hibernate;
// Generated 21 May, 2016 5:04:19 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * MembershipClassList generated by hbm2java
 */
public class MembershipClassList  implements java.io.Serializable {


     private String membershipClassName;
     private Set<Membership> memberships = new HashSet<Membership>(0);

    public MembershipClassList() {
    }

	
    public MembershipClassList(String membershipClassName) {
        this.membershipClassName = membershipClassName;
    }
    public MembershipClassList(String membershipClassName, Set<Membership> memberships) {
       this.membershipClassName = membershipClassName;
       this.memberships = memberships;
    }
   
    public String getMembershipClassName() {
        return this.membershipClassName;
    }
    
    public void setMembershipClassName(String membershipClassName) {
        this.membershipClassName = membershipClassName;
    }
    public Set<Membership> getMemberships() {
        return this.memberships;
    }
    
    public void setMemberships(Set<Membership> memberships) {
        this.memberships = memberships;
    }




}


