package hibernate;
// Generated 21 May, 2016 5:04:19 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Membership generated by hbm2java
 */
public class Membership  implements java.io.Serializable {


     private MembershipId id;
     private Contact contact;
     private MembershipClassList membershipClassList;
     private ModeOfSendingReceiptList modeOfSendingReceiptList;
     private PaymentModeList paymentModeList;
     private String createdBy;
     private String explainIfOtherClass;
     private Date startMembership;
     private Date endMembership;
     private Float subscriptionAmount;
     private String explainIfOtherPayment;
     private String extTransactionRef;
     private String receiptNumber;
     private Date receiptDate;
     private String explainIfOtherReceipt;
     private String remarks;

    public Membership() {
    }

	
    public Membership(MembershipId id, Contact contact, String createdBy) {
        this.id = id;
        this.contact = contact;
        this.createdBy = createdBy;
    }
    public Membership(MembershipId id, Contact contact, MembershipClassList membershipClassList, ModeOfSendingReceiptList modeOfSendingReceiptList, PaymentModeList paymentModeList, String createdBy, String explainIfOtherClass, Date startMembership, Date endMembership, Float subscriptionAmount, String explainIfOtherPayment, String extTransactionRef, String receiptNumber, Date receiptDate, String explainIfOtherReceipt, String remarks) {
       this.id = id;
       this.contact = contact;
       this.membershipClassList = membershipClassList;
       this.modeOfSendingReceiptList = modeOfSendingReceiptList;
       this.paymentModeList = paymentModeList;
       this.createdBy = createdBy;
       this.explainIfOtherClass = explainIfOtherClass;
       this.startMembership = startMembership;
       this.endMembership = endMembership;
       this.subscriptionAmount = subscriptionAmount;
       this.explainIfOtherPayment = explainIfOtherPayment;
       this.extTransactionRef = extTransactionRef;
       this.receiptNumber = receiptNumber;
       this.receiptDate = receiptDate;
       this.explainIfOtherReceipt = explainIfOtherReceipt;
       this.remarks = remarks;
    }
   
    public MembershipId getId() {
        return this.id;
    }
    
    public void setId(MembershipId id) {
        this.id = id;
    }
    public Contact getContact() {
        return this.contact;
    }
    
    public void setContact(Contact contact) {
        this.contact = contact;
    }
    public MembershipClassList getMembershipClassList() {
        return this.membershipClassList;
    }
    
    public void setMembershipClassList(MembershipClassList membershipClassList) {
        this.membershipClassList = membershipClassList;
    }
    public ModeOfSendingReceiptList getModeOfSendingReceiptList() {
        return this.modeOfSendingReceiptList;
    }
    
    public void setModeOfSendingReceiptList(ModeOfSendingReceiptList modeOfSendingReceiptList) {
        this.modeOfSendingReceiptList = modeOfSendingReceiptList;
    }
    public PaymentModeList getPaymentModeList() {
        return this.paymentModeList;
    }
    
    public void setPaymentModeList(PaymentModeList paymentModeList) {
        this.paymentModeList = paymentModeList;
    }
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }
    public String getExplainIfOtherClass() {
        return this.explainIfOtherClass;
    }
    
    public void setExplainIfOtherClass(String explainIfOtherClass) {
        this.explainIfOtherClass = explainIfOtherClass;
    }
    public Date getStartMembership() {
        return this.startMembership;
    }
    
    public void setStartMembership(Date startMembership) {
        this.startMembership = startMembership;
    }
    public Date getEndMembership() {
        return this.endMembership;
    }
    
    public void setEndMembership(Date endMembership) {
        this.endMembership = endMembership;
    }
    public Float getSubscriptionAmount() {
        return this.subscriptionAmount;
    }
    
    public void setSubscriptionAmount(Float subscriptionAmount) {
        this.subscriptionAmount = subscriptionAmount;
    }
    public String getExplainIfOtherPayment() {
        return this.explainIfOtherPayment;
    }
    
    public void setExplainIfOtherPayment(String explainIfOtherPayment) {
        this.explainIfOtherPayment = explainIfOtherPayment;
    }
    public String getExtTransactionRef() {
        return this.extTransactionRef;
    }
    
    public void setExtTransactionRef(String extTransactionRef) {
        this.extTransactionRef = extTransactionRef;
    }
    public String getReceiptNumber() {
        return this.receiptNumber;
    }
    
    public void setReceiptNumber(String receiptNumber) {
        this.receiptNumber = receiptNumber;
    }
    public Date getReceiptDate() {
        return this.receiptDate;
    }
    
    public void setReceiptDate(Date receiptDate) {
        this.receiptDate = receiptDate;
    }
    public String getExplainIfOtherReceipt() {
        return this.explainIfOtherReceipt;
    }
    
    public void setExplainIfOtherReceipt(String explainIfOtherReceipt) {
        this.explainIfOtherReceipt = explainIfOtherReceipt;
    }
    public String getRemarks() {
        return this.remarks;
    }
    
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }




}


