package hibernate;
// Generated 21 May, 2016 5:04:19 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * ModeOfSendingReceiptList generated by hbm2java
 */
public class ModeOfSendingReceiptList  implements java.io.Serializable {


     private String receiptModeName;
     private Set<Membership> memberships = new HashSet<Membership>(0);

    public ModeOfSendingReceiptList() {
    }

	
    public ModeOfSendingReceiptList(String receiptModeName) {
        this.receiptModeName = receiptModeName;
    }
    public ModeOfSendingReceiptList(String receiptModeName, Set<Membership> memberships) {
       this.receiptModeName = receiptModeName;
       this.memberships = memberships;
    }
   
    public String getReceiptModeName() {
        return this.receiptModeName;
    }
    
    public void setReceiptModeName(String receiptModeName) {
        this.receiptModeName = receiptModeName;
    }
    public Set<Membership> getMemberships() {
        return this.memberships;
    }
    
    public void setMemberships(Set<Membership> memberships) {
        this.memberships = memberships;
    }




}


