package hibernate;
// Generated 14 May, 2016 6:30:30 PM by Hibernate Tools 4.3.1



/**
 * ModeOfSendingReceipt generated by hbm2java
 */
public class ModeOfSendingReceipt  implements java.io.Serializable {


     private String receiptModeName;

    public ModeOfSendingReceipt() {
    }

    public ModeOfSendingReceipt(String receiptModeName) {
       this.receiptModeName = receiptModeName;
    }
   
    public String getReceiptModeName() {
        return this.receiptModeName;
    }
    
    public void setReceiptModeName(String receiptModeName) {
        this.receiptModeName = receiptModeName;
    }




}


