package hibernate;
// Generated 14 May, 2016 6:30:30 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Notice generated by hbm2java
 */
public class Notice  implements java.io.Serializable {


     private int noticeId;
     private int eventId;
     private int createdBy;
     private Date dateCreated;
     private Integer activelyPushout;
     private String messageTitle;
     private String messageContent;
     private String status;

    public Notice() {
    }

	
    public Notice(int noticeId, int eventId, int createdBy, Date dateCreated, String messageTitle) {
        this.noticeId = noticeId;
        this.eventId = eventId;
        this.createdBy = createdBy;
        this.dateCreated = dateCreated;
        this.messageTitle = messageTitle;
    }
    public Notice(int noticeId, int eventId, int createdBy, Date dateCreated, Integer activelyPushout, String messageTitle, String messageContent, String status) {
       this.noticeId = noticeId;
       this.eventId = eventId;
       this.createdBy = createdBy;
       this.dateCreated = dateCreated;
       this.activelyPushout = activelyPushout;
       this.messageTitle = messageTitle;
       this.messageContent = messageContent;
       this.status = status;
    }
   
    public int getNoticeId() {
        return this.noticeId;
    }
    
    public void setNoticeId(int noticeId) {
        this.noticeId = noticeId;
    }
    public int getEventId() {
        return this.eventId;
    }
    
    public void setEventId(int eventId) {
        this.eventId = eventId;
    }
    public int getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(int createdBy) {
        this.createdBy = createdBy;
    }
    public Date getDateCreated() {
        return this.dateCreated;
    }
    
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }
    public Integer getActivelyPushout() {
        return this.activelyPushout;
    }
    
    public void setActivelyPushout(Integer activelyPushout) {
        this.activelyPushout = activelyPushout;
    }
    public String getMessageTitle() {
        return this.messageTitle;
    }
    
    public void setMessageTitle(String messageTitle) {
        this.messageTitle = messageTitle;
    }
    public String getMessageContent() {
        return this.messageContent;
    }
    
    public void setMessageContent(String messageContent) {
        this.messageContent = messageContent;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }




}


