package hibernate;
// Generated 21 May, 2016 5:04:19 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * OfficeList generated by hbm2java
 */
public class OfficeList  implements java.io.Serializable {


     private int officeId;
     private String officeHeldName;
     private String description;
     private Set<OfficeHeld> officeHelds = new HashSet<OfficeHeld>(0);

    public OfficeList() {
    }

	
    public OfficeList(int officeId, String officeHeldName) {
        this.officeId = officeId;
        this.officeHeldName = officeHeldName;
    }
    public OfficeList(int officeId, String officeHeldName, String description, Set<OfficeHeld> officeHelds) {
       this.officeId = officeId;
       this.officeHeldName = officeHeldName;
       this.description = description;
       this.officeHelds = officeHelds;
    }
   
    public int getOfficeId() {
        return this.officeId;
    }
    
    public void setOfficeId(int officeId) {
        this.officeId = officeId;
    }
    public String getOfficeHeldName() {
        return this.officeHeldName;
    }
    
    public void setOfficeHeldName(String officeHeldName) {
        this.officeHeldName = officeHeldName;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Set<OfficeHeld> getOfficeHelds() {
        return this.officeHelds;
    }
    
    public void setOfficeHelds(Set<OfficeHeld> officeHelds) {
        this.officeHelds = officeHelds;
    }




}


