package hibernate;
// Generated 21 May, 2016 5:04:19 PM by Hibernate Tools 4.3.1



/**
 * OfficeHeldId generated by hbm2java
 */
public class OfficeHeldId  implements java.io.Serializable {


     private int contactId;
     private int officeId;

    public OfficeHeldId() {
    }

    public OfficeHeldId(int contactId, int officeId) {
       this.contactId = contactId;
       this.officeId = officeId;
    }
   
    public int getContactId() {
        return this.contactId;
    }
    
    public void setContactId(int contactId) {
        this.contactId = contactId;
    }
    public int getOfficeId() {
        return this.officeId;
    }
    
    public void setOfficeId(int officeId) {
        this.officeId = officeId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof OfficeHeldId) ) return false;
		 OfficeHeldId castOther = ( OfficeHeldId ) other; 
         
		 return (this.getContactId()==castOther.getContactId())
 && (this.getOfficeId()==castOther.getOfficeId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getContactId();
         result = 37 * result + this.getOfficeId();
         return result;
   }   


}


