package hibernate;
// Generated 14 May, 2016 6:30:30 PM by Hibernate Tools 4.3.1



/**
 * OfficeHeld generated by hbm2java
 */
public class OfficeHeld  implements java.io.Serializable {


     private int officeId;
     private String officeHeldName;
     private String description;

    public OfficeHeld() {
    }

	
    public OfficeHeld(int officeId, String officeHeldName) {
        this.officeId = officeId;
        this.officeHeldName = officeHeldName;
    }
    public OfficeHeld(int officeId, String officeHeldName, String description) {
       this.officeId = officeId;
       this.officeHeldName = officeHeldName;
       this.description = description;
    }
   
    public int getOfficeId() {
        return this.officeId;
    }
    
    public void setOfficeId(int officeId) {
        this.officeId = officeId;
    }
    public String getOfficeHeldName() {
        return this.officeHeldName;
    }
    
    public void setOfficeHeldName(String officeHeldName) {
        this.officeHeldName = officeHeldName;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }




}


