package hibernate;
// Generated 21 May, 2016 5:04:19 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * OfficeHeld generated by hbm2java
 */
public class OfficeHeld  implements java.io.Serializable {


     private OfficeHeldId id;
     private Contact contact;
     private OfficeList officeList;
     private Date dateCreated;
     private String createdBy;
     private Date startOffice;
     private Date endOffice;
     private String remarks;

    public OfficeHeld() {
    }

	
    public OfficeHeld(OfficeHeldId id, Contact contact, OfficeList officeList, Date dateCreated, String createdBy, Date startOffice, Date endOffice) {
        this.id = id;
        this.contact = contact;
        this.officeList = officeList;
        this.dateCreated = dateCreated;
        this.createdBy = createdBy;
        this.startOffice = startOffice;
        this.endOffice = endOffice;
    }
    public OfficeHeld(OfficeHeldId id, Contact contact, OfficeList officeList, Date dateCreated, String createdBy, Date startOffice, Date endOffice, String remarks) {
       this.id = id;
       this.contact = contact;
       this.officeList = officeList;
       this.dateCreated = dateCreated;
       this.createdBy = createdBy;
       this.startOffice = startOffice;
       this.endOffice = endOffice;
       this.remarks = remarks;
    }
   
    public OfficeHeldId getId() {
        return this.id;
    }
    
    public void setId(OfficeHeldId id) {
        this.id = id;
    }
    public Contact getContact() {
        return this.contact;
    }
    
    public void setContact(Contact contact) {
        this.contact = contact;
    }
    public OfficeList getOfficeList() {
        return this.officeList;
    }
    
    public void setOfficeList(OfficeList officeList) {
        this.officeList = officeList;
    }
    public Date getDateCreated() {
        return this.dateCreated;
    }
    
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }
    public Date getStartOffice() {
        return this.startOffice;
    }
    
    public void setStartOffice(Date startOffice) {
        this.startOffice = startOffice;
    }
    public Date getEndOffice() {
        return this.endOffice;
    }
    
    public void setEndOffice(Date endOffice) {
        this.endOffice = endOffice;
    }
    public String getRemarks() {
        return this.remarks;
    }
    
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }




}


