package hibernate;
// Generated 21 May, 2016 5:04:19 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * PaymentModeList generated by hbm2java
 */
public class PaymentModeList  implements java.io.Serializable {


     private String paymentModeName;
     private Set<Donation> donations = new HashSet<Donation>(0);
     private Set<Membership> memberships = new HashSet<Membership>(0);

    public PaymentModeList() {
    }

	
    public PaymentModeList(String paymentModeName) {
        this.paymentModeName = paymentModeName;
    }
    public PaymentModeList(String paymentModeName, Set<Donation> donations, Set<Membership> memberships) {
       this.paymentModeName = paymentModeName;
       this.donations = donations;
       this.memberships = memberships;
    }
   
    public String getPaymentModeName() {
        return this.paymentModeName;
    }
    
    public void setPaymentModeName(String paymentModeName) {
        this.paymentModeName = paymentModeName;
    }
    public Set<Donation> getDonations() {
        return this.donations;
    }
    
    public void setDonations(Set<Donation> donations) {
        this.donations = donations;
    }
    public Set<Membership> getMemberships() {
        return this.memberships;
    }
    
    public void setMemberships(Set<Membership> memberships) {
        this.memberships = memberships;
    }




}


