package hibernate;
// Generated 14 May, 2016 6:30:30 PM by Hibernate Tools 4.3.1



/**
 * PaymentMode generated by hbm2java
 */
public class PaymentMode  implements java.io.Serializable {


     private String paymentModeName;

    public PaymentMode() {
    }

    public PaymentMode(String paymentModeName) {
       this.paymentModeName = paymentModeName;
    }
   
    public String getPaymentModeName() {
        return this.paymentModeName;
    }
    
    public void setPaymentModeName(String paymentModeName) {
        this.paymentModeName = paymentModeName;
    }




}


