package hibernate;
// Generated 14 May, 2016 6:30:30 PM by Hibernate Tools 4.3.1



/**
 * PermissionLevel generated by hbm2java
 */
public class PermissionLevel  implements java.io.Serializable {


     private String permission;

    public PermissionLevel() {
    }

    public PermissionLevel(String permission) {
       this.permission = permission;
    }
   
    public String getPermission() {
        return this.permission;
    }
    
    public void setPermission(String permission) {
        this.permission = permission;
    }




}


