package hibernate;
// Generated 21 May, 2016 5:04:19 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * PermissionLevelList generated by hbm2java
 */
public class PermissionLevelList  implements java.io.Serializable {


     private String permission;
     private String description;
     private Set<TeamJoin> teamJoins = new HashSet<TeamJoin>(0);

    public PermissionLevelList() {
    }

	
    public PermissionLevelList(String permission) {
        this.permission = permission;
    }
    public PermissionLevelList(String permission, String description, Set<TeamJoin> teamJoins) {
       this.permission = permission;
       this.description = description;
       this.teamJoins = teamJoins;
    }
   
    public String getPermission() {
        return this.permission;
    }
    
    public void setPermission(String permission) {
        this.permission = permission;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Set<TeamJoin> getTeamJoins() {
        return this.teamJoins;
    }
    
    public void setTeamJoins(Set<TeamJoin> teamJoins) {
        this.teamJoins = teamJoins;
    }




}


