package hibernate;
// Generated 21 May, 2016 5:04:19 PM by Hibernate Tools 4.3.1



/**
 * PhoneId generated by hbm2java
 */
public class PhoneId  implements java.io.Serializable {


     private int contactId;
     private String phoneNumber;

    public PhoneId() {
    }

    public PhoneId(int contactId, String phoneNumber) {
       this.contactId = contactId;
       this.phoneNumber = phoneNumber;
    }
   
    public int getContactId() {
        return this.contactId;
    }
    
    public void setContactId(int contactId) {
        this.contactId = contactId;
    }
    public String getPhoneNumber() {
        return this.phoneNumber;
    }
    
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PhoneId) ) return false;
		 PhoneId castOther = ( PhoneId ) other; 
         
		 return (this.getContactId()==castOther.getContactId())
 && ( (this.getPhoneNumber()==castOther.getPhoneNumber()) || ( this.getPhoneNumber()!=null && castOther.getPhoneNumber()!=null && this.getPhoneNumber().equals(castOther.getPhoneNumber()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getContactId();
         result = 37 * result + ( getPhoneNumber() == null ? 0 : this.getPhoneNumber().hashCode() );
         return result;
   }   


}


