package hibernate;
// Generated 21 May, 2016 5:04:19 PM by Hibernate Tools 4.3.1



/**
 * ProxyId generated by hbm2java
 */
public class ProxyId  implements java.io.Serializable {


     private int contactId;
     private int proxyId;

    public ProxyId() {
    }

    public ProxyId(int contactId, int proxyId) {
       this.contactId = contactId;
       this.proxyId = proxyId;
    }
   
    public int getContactId() {
        return this.contactId;
    }
    
    public void setContactId(int contactId) {
        this.contactId = contactId;
    }
    public int getProxyId() {
        return this.proxyId;
    }
    
    public void setProxyId(int proxyId) {
        this.proxyId = proxyId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ProxyId) ) return false;
		 ProxyId castOther = ( ProxyId ) other; 
         
		 return (this.getContactId()==castOther.getContactId())
 && (this.getProxyId()==castOther.getProxyId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getContactId();
         result = 37 * result + this.getProxyId();
         return result;
   }   


}


