package hibernate;
// Generated 21 May, 2016 5:04:19 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Proxy generated by hbm2java
 */
public class Proxy  implements java.io.Serializable {


     private ProxyId id;
     private Contact contactByProxyId;
     private Contact contactByContactId;
     private String createdBy;
     private String proxyStanding;
     private Date dateObsolete;
     private String remarks;

    public Proxy() {
    }

	
    public Proxy(ProxyId id, Contact contactByProxyId, Contact contactByContactId, String createdBy) {
        this.id = id;
        this.contactByProxyId = contactByProxyId;
        this.contactByContactId = contactByContactId;
        this.createdBy = createdBy;
    }
    public Proxy(ProxyId id, Contact contactByProxyId, Contact contactByContactId, String createdBy, String proxyStanding, Date dateObsolete, String remarks) {
       this.id = id;
       this.contactByProxyId = contactByProxyId;
       this.contactByContactId = contactByContactId;
       this.createdBy = createdBy;
       this.proxyStanding = proxyStanding;
       this.dateObsolete = dateObsolete;
       this.remarks = remarks;
    }
   
    public ProxyId getId() {
        return this.id;
    }
    
    public void setId(ProxyId id) {
        this.id = id;
    }
    public Contact getContactByProxyId() {
        return this.contactByProxyId;
    }
    
    public void setContactByProxyId(Contact contactByProxyId) {
        this.contactByProxyId = contactByProxyId;
    }
    public Contact getContactByContactId() {
        return this.contactByContactId;
    }
    
    public void setContactByContactId(Contact contactByContactId) {
        this.contactByContactId = contactByContactId;
    }
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }
    public String getProxyStanding() {
        return this.proxyStanding;
    }
    
    public void setProxyStanding(String proxyStanding) {
        this.proxyStanding = proxyStanding;
    }
    public Date getDateObsolete() {
        return this.dateObsolete;
    }
    
    public void setDateObsolete(Date dateObsolete) {
        this.dateObsolete = dateObsolete;
    }
    public String getRemarks() {
        return this.remarks;
    }
    
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }




}


