package hibernate;
// Generated 21 May, 2016 5:04:19 PM by Hibernate Tools 4.3.1



/**
 * SkillAssignmentId generated by hbm2java
 */
public class SkillAssignmentId  implements java.io.Serializable {


     private int contactId;
     private String skillName;

    public SkillAssignmentId() {
    }

    public SkillAssignmentId(int contactId, String skillName) {
       this.contactId = contactId;
       this.skillName = skillName;
    }
   
    public int getContactId() {
        return this.contactId;
    }
    
    public void setContactId(int contactId) {
        this.contactId = contactId;
    }
    public String getSkillName() {
        return this.skillName;
    }
    
    public void setSkillName(String skillName) {
        this.skillName = skillName;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof SkillAssignmentId) ) return false;
		 SkillAssignmentId castOther = ( SkillAssignmentId ) other; 
         
		 return (this.getContactId()==castOther.getContactId())
 && ( (this.getSkillName()==castOther.getSkillName()) || ( this.getSkillName()!=null && castOther.getSkillName()!=null && this.getSkillName().equals(castOther.getSkillName()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getContactId();
         result = 37 * result + ( getSkillName() == null ? 0 : this.getSkillName().hashCode() );
         return result;
   }   


}


