package hibernate;
// Generated 21 May, 2016 5:04:19 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * SkillAssignment generated by hbm2java
 */
public class SkillAssignment  implements java.io.Serializable {


     private SkillAssignmentId id;
     private Contact contact;
     private LsaClassList lsaClassList;
     private Date dateCreated;
     private String createdBy;
     private String explainIfOther;
     private Date dateObsolete;
     private String remarks;

    public SkillAssignment() {
    }

	
    public SkillAssignment(SkillAssignmentId id, Contact contact, LsaClassList lsaClassList, String createdBy) {
        this.id = id;
        this.contact = contact;
        this.lsaClassList = lsaClassList;
        this.createdBy = createdBy;
    }
    public SkillAssignment(SkillAssignmentId id, Contact contact, LsaClassList lsaClassList, Date dateCreated, String createdBy, String explainIfOther, Date dateObsolete, String remarks) {
       this.id = id;
       this.contact = contact;
       this.lsaClassList = lsaClassList;
       this.dateCreated = dateCreated;
       this.createdBy = createdBy;
       this.explainIfOther = explainIfOther;
       this.dateObsolete = dateObsolete;
       this.remarks = remarks;
    }
   
    public SkillAssignmentId getId() {
        return this.id;
    }
    
    public void setId(SkillAssignmentId id) {
        this.id = id;
    }
    public Contact getContact() {
        return this.contact;
    }
    
    public void setContact(Contact contact) {
        this.contact = contact;
    }
    public LsaClassList getLsaClassList() {
        return this.lsaClassList;
    }
    
    public void setLsaClassList(LsaClassList lsaClassList) {
        this.lsaClassList = lsaClassList;
    }
    public Date getDateCreated() {
        return this.dateCreated;
    }
    
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }
    public String getExplainIfOther() {
        return this.explainIfOther;
    }
    
    public void setExplainIfOther(String explainIfOther) {
        this.explainIfOther = explainIfOther;
    }
    public Date getDateObsolete() {
        return this.dateObsolete;
    }
    
    public void setDateObsolete(Date dateObsolete) {
        this.dateObsolete = dateObsolete;
    }
    public String getRemarks() {
        return this.remarks;
    }
    
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }




}


