package hibernate;
// Generated 14 May, 2016 6:30:30 PM by Hibernate Tools 4.3.1



/**
 * TeamAffiliation generated by hbm2java
 */
public class TeamAffiliation  implements java.io.Serializable {


     private String teamName;

    public TeamAffiliation() {
    }

    public TeamAffiliation(String teamName) {
       this.teamName = teamName;
    }
   
    public String getTeamName() {
        return this.teamName;
    }
    
    public void setTeamName(String teamName) {
        this.teamName = teamName;
    }




}


