package hibernate;
// Generated 21 May, 2016 5:04:19 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * TeamJoin generated by hbm2java
 */
public class TeamJoin  implements java.io.Serializable {


     private TeamJoinId id;
     private Contact contact;
     private PermissionLevelList permissionLevelList;
     private TeamAffiliationList teamAffiliationList;
     private Date dateCreated;
     private String createdBy;
     private String explainIfOther;
     private String subteam;
     private Date dateObsolete;
     private String remarks;

    public TeamJoin() {
    }

	
    public TeamJoin(TeamJoinId id, Contact contact, PermissionLevelList permissionLevelList, TeamAffiliationList teamAffiliationList, Date dateCreated, String createdBy) {
        this.id = id;
        this.contact = contact;
        this.permissionLevelList = permissionLevelList;
        this.teamAffiliationList = teamAffiliationList;
        this.dateCreated = dateCreated;
        this.createdBy = createdBy;
    }
    public TeamJoin(TeamJoinId id, Contact contact, PermissionLevelList permissionLevelList, TeamAffiliationList teamAffiliationList, Date dateCreated, String createdBy, String explainIfOther, String subteam, Date dateObsolete, String remarks) {
       this.id = id;
       this.contact = contact;
       this.permissionLevelList = permissionLevelList;
       this.teamAffiliationList = teamAffiliationList;
       this.dateCreated = dateCreated;
       this.createdBy = createdBy;
       this.explainIfOther = explainIfOther;
       this.subteam = subteam;
       this.dateObsolete = dateObsolete;
       this.remarks = remarks;
    }
   
    public TeamJoinId getId() {
        return this.id;
    }
    
    public void setId(TeamJoinId id) {
        this.id = id;
    }
    public Contact getContact() {
        return this.contact;
    }
    
    public void setContact(Contact contact) {
        this.contact = contact;
    }
    public PermissionLevelList getPermissionLevelList() {
        return this.permissionLevelList;
    }
    
    public void setPermissionLevelList(PermissionLevelList permissionLevelList) {
        this.permissionLevelList = permissionLevelList;
    }
    public TeamAffiliationList getTeamAffiliationList() {
        return this.teamAffiliationList;
    }
    
    public void setTeamAffiliationList(TeamAffiliationList teamAffiliationList) {
        this.teamAffiliationList = teamAffiliationList;
    }
    public Date getDateCreated() {
        return this.dateCreated;
    }
    
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }
    public String getExplainIfOther() {
        return this.explainIfOther;
    }
    
    public void setExplainIfOther(String explainIfOther) {
        this.explainIfOther = explainIfOther;
    }
    public String getSubteam() {
        return this.subteam;
    }
    
    public void setSubteam(String subteam) {
        this.subteam = subteam;
    }
    public Date getDateObsolete() {
        return this.dateObsolete;
    }
    
    public void setDateObsolete(Date dateObsolete) {
        this.dateObsolete = dateObsolete;
    }
    public String getRemarks() {
        return this.remarks;
    }
    
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }




}


