package hibernate;
// Generated 21 May, 2016 5:04:19 PM by Hibernate Tools 4.3.1



/**
 * TeamJoinId generated by hbm2java
 */
public class TeamJoinId  implements java.io.Serializable {


     private int contactId;
     private String teamName;
     private String permission;

    public TeamJoinId() {
    }

    public TeamJoinId(int contactId, String teamName, String permission) {
       this.contactId = contactId;
       this.teamName = teamName;
       this.permission = permission;
    }
   
    public int getContactId() {
        return this.contactId;
    }
    
    public void setContactId(int contactId) {
        this.contactId = contactId;
    }
    public String getTeamName() {
        return this.teamName;
    }
    
    public void setTeamName(String teamName) {
        this.teamName = teamName;
    }
    public String getPermission() {
        return this.permission;
    }
    
    public void setPermission(String permission) {
        this.permission = permission;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TeamJoinId) ) return false;
		 TeamJoinId castOther = ( TeamJoinId ) other; 
         
		 return (this.getContactId()==castOther.getContactId())
 && ( (this.getTeamName()==castOther.getTeamName()) || ( this.getTeamName()!=null && castOther.getTeamName()!=null && this.getTeamName().equals(castOther.getTeamName()) ) )
 && ( (this.getPermission()==castOther.getPermission()) || ( this.getPermission()!=null && castOther.getPermission()!=null && this.getPermission().equals(castOther.getPermission()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getContactId();
         result = 37 * result + ( getTeamName() == null ? 0 : this.getTeamName().hashCode() );
         result = 37 * result + ( getPermission() == null ? 0 : this.getPermission().hashCode() );
         return result;
   }   


}


