package hibernate;
// Generated 21 May, 2016 5:04:19 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * TrainingCertificated generated by hbm2java
 */
public class TrainingCertificated  implements java.io.Serializable {


     private int certificationId;
     private Contact contact;
     private Event event;
     private String createdBy;
     private Date dateCreated;
     private String explainIfOther;
     private String remarks;

    public TrainingCertificated() {
    }

	
    public TrainingCertificated(int certificationId, Contact contact, Event event, String createdBy, Date dateCreated) {
        this.certificationId = certificationId;
        this.contact = contact;
        this.event = event;
        this.createdBy = createdBy;
        this.dateCreated = dateCreated;
    }
    public TrainingCertificated(int certificationId, Contact contact, Event event, String createdBy, Date dateCreated, String explainIfOther, String remarks) {
       this.certificationId = certificationId;
       this.contact = contact;
       this.event = event;
       this.createdBy = createdBy;
       this.dateCreated = dateCreated;
       this.explainIfOther = explainIfOther;
       this.remarks = remarks;
    }
   
    public int getCertificationId() {
        return this.certificationId;
    }
    
    public void setCertificationId(int certificationId) {
        this.certificationId = certificationId;
    }
    public Contact getContact() {
        return this.contact;
    }
    
    public void setContact(Contact contact) {
        this.contact = contact;
    }
    public Event getEvent() {
        return this.event;
    }
    
    public void setEvent(Event event) {
        this.event = event;
    }
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }
    public Date getDateCreated() {
        return this.dateCreated;
    }
    
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }
    public String getExplainIfOther() {
        return this.explainIfOther;
    }
    
    public void setExplainIfOther(String explainIfOther) {
        this.explainIfOther = explainIfOther;
    }
    public String getRemarks() {
        return this.remarks;
    }
    
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }




}


