package hibernate;
// Generated 14 May, 2016 6:30:30 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Training generated by hbm2java
 */
public class Training  implements java.io.Serializable {


     private int trainingId;
     private int trainingBy;
     private int createdBy;
     private Date dateCreated;
     private String explainIfOther;
     private String trainingCourse;
     private Date trainingDate;
     private String remarks;

    public Training() {
    }

	
    public Training(int trainingId, int trainingBy, int createdBy, Date dateCreated) {
        this.trainingId = trainingId;
        this.trainingBy = trainingBy;
        this.createdBy = createdBy;
        this.dateCreated = dateCreated;
    }
    public Training(int trainingId, int trainingBy, int createdBy, Date dateCreated, String explainIfOther, String trainingCourse, Date trainingDate, String remarks) {
       this.trainingId = trainingId;
       this.trainingBy = trainingBy;
       this.createdBy = createdBy;
       this.dateCreated = dateCreated;
       this.explainIfOther = explainIfOther;
       this.trainingCourse = trainingCourse;
       this.trainingDate = trainingDate;
       this.remarks = remarks;
    }
   
    public int getTrainingId() {
        return this.trainingId;
    }
    
    public void setTrainingId(int trainingId) {
        this.trainingId = trainingId;
    }
    public int getTrainingBy() {
        return this.trainingBy;
    }
    
    public void setTrainingBy(int trainingBy) {
        this.trainingBy = trainingBy;
    }
    public int getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(int createdBy) {
        this.createdBy = createdBy;
    }
    public Date getDateCreated() {
        return this.dateCreated;
    }
    
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }
    public String getExplainIfOther() {
        return this.explainIfOther;
    }
    
    public void setExplainIfOther(String explainIfOther) {
        this.explainIfOther = explainIfOther;
    }
    public String getTrainingCourse() {
        return this.trainingCourse;
    }
    
    public void setTrainingCourse(String trainingCourse) {
        this.trainingCourse = trainingCourse;
    }
    public Date getTrainingDate() {
        return this.trainingDate;
    }
    
    public void setTrainingDate(Date trainingDate) {
        this.trainingDate = trainingDate;
    }
    public String getRemarks() {
        return this.remarks;
    }
    
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }




}


