package hibernate;
// Generated 14 May, 2016 6:30:30 PM by Hibernate Tools 4.3.1



/**
 * TypeOfContact generated by hbm2java
 */
public class TypeOfContact  implements java.io.Serializable {


     private String contactType;

    public TypeOfContact() {
    }

    public TypeOfContact(String contactType) {
       this.contactType = contactType;
    }
   
    public String getContactType() {
        return this.contactType;
    }
    
    public void setContactType(String contactType) {
        this.contactType = contactType;
    }




}


